# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine AS build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install --ignore-scripts --production
COPY . ./

FROM node:lts-alpine
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["node", "src/index.js"]
